### ISSUE TITLE
Add textMatches with boolean return type for ValueComponents

### ISSUE THREAD

**Issue by fschwedl-hsdg** [AludraTest/aludratest#79]
Add an equivalent to assertTextMatches() with a boolean return type to make it possible to e.g. check if text contains or text starts with a given String parameter.

**Comment by falbrech-hsdg** [comment]
Will not be implemented. Can easily be implemented as this:

new ContainsIgnoreCaseTrimmedValidator().valid(myComponent.getText());

(or any validator class you require)

The component assert* classes are helpful because they all trigger the standard AludraTest assertion failed exceptions. But a "textMatches()" method would only be overhead, as it would simply contain the line from above.
